spring.datasource.url=jdbc:mysql://ug4fgm5wec4svp9j:BC6UF34wRxWrgC7YrUQx@b3jxeunxp2wofleni1m6-mysql.services.clever-cloud.com:3306/b3jxeunxp2wofleni1m6
spring.datasource.username=ug4fgm5wec4svp9j
spring.datasource.password=BC6UF34wRxWrgC7YrUQx
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect





#spring.application.name=libros

#spring.datasource.url=jdbc:mysql://localhost:3306/libros
#spring.datasource.username=root
#spring.datasource.password=1234
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true


